<div class="wrap">
	<?php wp_nonce_field( 'gou_organ' ); ?>
	<input type="hidden" id="year" value="<?php echo $year; ?>" />
	<h2>
		<?php echo $title; ?> <?php echo $year; ?>
		<a href="?post_type=gou_reservation&page=gou_booking_grid&year=<?php echo $year - 1; ?>" class="add-new-h2">← <?php echo $year - 1; ?>–<?php echo $year; ?></a>
		<a href="?post_type=gou_reservation&page=gou_booking_grid&year=<?php echo $year + 1; ?>" class="add-new-h2"><?php echo $year + 1; ?>–<?php echo $year + 2; ?> →</a>
	</h2>
	<p>
		<a id="new_reservation" class="button-primary">Ajouter</a>
	</p>
	<div id="gou_booking_grid">
		<?php echo $calendar; ?>
	</div>
</div>
<script>
	var selection = new DragSelect('gou_booking_grid', '.day', {
		'singleRange':     true,
		'singleSelection': true
	});
	
	document.addEventListener('click', function() {
		selection.clearSelection();
	});
	
	document.getElementById('new_reservation').addEventListener('click', function() {
		var start = null;
		var end = null;
		
		selection.getSelection().forEach(function(/*Element*/ i) {
			var date = i.getAttribute('data-date');
			
			if(start === null || date < start) {
				start = date;
			}
			
			if(end === null || date > end) {
				end = date;
			}
		});
		
		var location = 'post-new.php?post_type=gou_reservation';
		
		if(start) {
			location += '&gou_booking_start=' + start; 
		}
		
		if(end) {
			location += '&gou_booking_end=' + end; 
		}
		
		window.location.href = location;
	});
</script>